// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parcial2_AP1_MiguelBetances.Api.DAL;

#nullable disable

namespace Parcial2_AP1_MiguelBetances.Api.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20240305030708_Modifiando_VehiulosDetalle")]
    partial class Modifiando_VehiulosDetalle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("Parcial2_AP1_MiguelBetances.Shared.Models.Accesorios", b =>
                {
                    b.Property<int>("AccesorioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripción")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AccesorioId");

                    b.ToTable("Accesorios");

                    b.HasData(
                        new
                        {
                            AccesorioId = 1,
                            Descripción = "Camara Trasera"
                        },
                        new
                        {
                            AccesorioId = 2,
                            Descripción = "Pantalla Interior"
                        },
                        new
                        {
                            AccesorioId = 3,
                            Descripción = "Interior en Piel"
                        },
                        new
                        {
                            AccesorioId = 4,
                            Descripción = "Sun Roof"
                        },
                        new
                        {
                            AccesorioId = 5,
                            Descripción = "Aros de Lujo"
                        });
                });

            modelBuilder.Entity("Parcial2_AP1_MiguelBetances.Shared.Models.Vehiculos", b =>
                {
                    b.Property<int>("VehiculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Costo")
                        .HasColumnType("REAL");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<double>("Gastos")
                        .HasColumnType("REAL");

                    b.HasKey("VehiculoId");

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("Parcial2_AP1_MiguelBetances.Shared.Models.VehiculosDetalle", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccesorioId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Valor")
                        .HasColumnType("REAL");

                    b.Property<int?>("VehiculoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VehiculosId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DetalleId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("VehiculosDetalle");
                });

            modelBuilder.Entity("Parcial2_AP1_MiguelBetances.Shared.Models.VehiculosDetalle", b =>
                {
                    b.HasOne("Parcial2_AP1_MiguelBetances.Shared.Models.Vehiculos", null)
                        .WithMany("VehiculosDetalle")
                        .HasForeignKey("VehiculoId");
                });

            modelBuilder.Entity("Parcial2_AP1_MiguelBetances.Shared.Models.Vehiculos", b =>
                {
                    b.Navigation("VehiculosDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
